### PR TITLE
Editor agnostic

### LINKED ISSUE #50: requires tinymce
if you are not using tinymce then any tour that was using it as an identifier is broken

image

### PR DESCRIPTION
**Pull request by brianteeman**
replaces the tinymce specific target with adminform which should work with all editors

fixes #50

### CODE REVIEW

**Comment by obuisard** [comment]
I was wondering if it is accessible to put the focus on the form here.

**Comment by brianteeman** [comment]
accessible - no idea but then nothing is with this tour

working - yes I tested with no-editor, tiny and codemirror

**Comment by obuisard** [comment]
I will work on the conflicts Brian

**Comment by brianteeman** [comment]
conflicts resolved

**Pull request closed without merging**
