### PR TITLE
Miscellaneous fixes

### PR DESCRIPTION
**Pull request by obuisard**
Pull Request for Issue #38, #39, #74, #85.

### Summary of Changes

Typos in order url task attribute
Fixed saving to asset table

### CODE REVIEW

**Comment by brianteeman** [comment]
tours is working - be aware that you have to refresh the page to refresh the module itself
probably should change the sql as well so that they dont all have a value of 1 in the ordering field

Steps however is not. Tried a few times by moving something from the end to the top. Looks ok. refresh and its then somewhere in the middle. verified this in the database by checking the ordering value

probably should also update the sql as for tours and remove the unused field step_no

**Comment by brianteeman** [comment]
updated my branch with the latest changes and made a video to show you what is happening. Should be obvious by the end and I bet its a very quick fix.

https://user-images.githubusercontent.com/1296369/218878373-1e478110-db7d-46f1-b8ff-60040c51fb12.mp4

**Comment by obuisard** [comment]
> updated my branch with the latest changes and made a video to show you what is happening. Should be obvious by the end and I bet its a very quick fix.

It was obvious indeed. The ordering number was taken from the tours table, not the steps table.
I have included the fix in this PR as a follow up to your video.

**Comment by brianteeman** [comment]
So the ordering now works correctly in the list etc

BUT
the ordering changes are not reflected in the tour itself. 

I did some checks and when you are running a tour the steps are run in ID order

**Comment by brianteeman** [comment]
just saw #100 not checked it yet but that looks like it addrsses the problem

**Pull request merged**
